include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/**
    
  errors:
    prefer_relative_imports: warning
    constant_identifier_names: warning
    non_constant_identifier_names: warning

linter:
  rules:
    prefer_const_constructors: true
    unawaited_futures: false
